rules:
  - No griefing.
  - Be respectful to other players.
  - No cheating or exploiting bugs.
  - Follow the instructions of server staff.
faq:
  - Q: How do I join the server?
    A: Use the IP address minecraft.example.com.
  - Q: What version of Minecraft is supported?
    A: We support the latest stable version of Minecraft.
  - Q: How can I become a server admin?
    A: Server admins are chosen from active and helpful members of the community.
  - Q: What are the server rules?
    A: Use /regler to see the rules.
